### ISSUE TITLE
Toggles enabled per request

### ISSUE THREAD

**Issue by mihai-stancu** [qandidate-labs/qandidate-toggle-bundle#114]
Hi,

Would it be feasible to alter qandidate-toggle to manage the feature toggles of a multi tenant app?

...wherein the same feature can be enabled for one tenant but disabled for another?

I'm open to writing a PR for this if you think this is feasible within the current architecture of the bundle.

Thanks,
Mihai

**Comment by wjzijderveld** [comment]
It's not completely clear to me what you're looking for, but to me it sounds like you're looking for a solution to create settings for your tenants. In my opinion that shouldn't be something part of qandidate-toggle, as feature toggles aren't meant for long lived settings (with some exceptions like emergency toggles).

But if you're looking to use toggles to enable a couple beta-testers, you can already do that with the context, for example with the [InSet Operator](https://github.com/qandidate-labs/qandidate-toggle/blob/6b763394dcc22476a80cdb5b900d7af928f7003d/test/Qandidate/Toggle/Operator/InSetTest.php).

**Comment by mihai-stancu** [comment]
> it sounds like you're looking for a solution to create settings for your tenants
Yes. Something in the same vein.

> feature toggles aren't meant for long lived settings
Understood.

Thank you.
