### ISSUE TITLE
[Suggestion] Use a less generic name for the Twig function

### ISSUE THREAD

**Issue by stof** [qandidate-labs/qandidate-toggle-bundle#2]
``is_active`` is  a pretty generic name. This has 2 issues:

- it has a high risk of conflicting with other Twig extensions
- it does not make it clear that you are talking about active features.

I suggest using ``toggle_is_active`` or ``feature_is_active`` (or maybe ``is_active_toggle`` or ``is_active_feature``) instead. What do you think about it ?

**Comment by wjzijderveld** [comment]
Closing, as this has been long fixed in #2 :)

**Comment by stof** [comment]
@wjzijderveld #2 is the current issue. I guess you meant #6

**Comment by wjzijderveld** [comment]
Oops, yes I did mean #6 :smile:
