### ISSUE TITLE
Allowing toggles to be created from symfony config

### ISSUE THREAD

**Issue by JerryVerhoef** [qandidate-labs/qandidate-toggle-bundle#21]
We would like to use the symfony config for creating the various in memory toggle. There is no easy way to do this at the moment. So we created a factory for this and made it part of the bundle. 

We still need to do some cleanup (reordering and combining some of the commits) but the code is working now. We are implementing it now. So after we tested in the field we finish the PR.

But for now you can already take look at the PR and comment.

**Comment by othillo** [comment]
fixed by https://github.com/qandidate-labs/qandidate-toggle-bundle/pull/39
