### ISSUE TITLE
What about tagging a new version 0.3.2 or 0.4.0

### ISSUE THREAD

**Issue by robertfausk** [qandidate-labs/qandidate-toggle-bundle#23]
Cause there are currently 9 commits in master since 0.3.1 https://github.com/qandidate-labs/qandidate-toggle-bundle/compare/0.3.1...master

Especially the removal of the symfony 2.8 deprecations would be nice.

**Comment by asm89** [comment]
:+1:

**Comment by asm89** [comment]
Here you go: https://github.com/qandidate-labs/qandidate-toggle-bundle/releases/tag/0.4.0.

**Comment by robertfausk** [comment]
Thx a lot!
