### ISSUE TITLE
dev-master points to non-existing branch

### ISSUE THREAD

**Issue by fatganz** [qandidate-labs/qandidate-toggle-bundle#27]
`dev-master` points to non-existing `0.5.x-dev` branch which prevents access​s to neither `master` or  `0.5.x-dev` branches in forks.
Maybe I am wrong here.

**Comment by wjzijderveld** [comment]
It is a `branch-alias`, read about it [here](https://getcomposer.org/doc/articles/aliases.md#branch-alias). It allows people to start using 0.5 before we actually tagged a 0.5 (when they allow dev dependencies).

**Comment by fatganz** [comment]
Sorry, mixed the left and right parts of the expression.
