### ISSUE TITLE
Create a new tag?

### ISSUE THREAD

**Issue by eriwin** [qandidate-labs/qandidate-toggle-bundle#73]
Could you tag a new version?  I would like to use the fix of #72 and not use "dev-master" in composer.json as a version constraint. Thank you!

Current changes on master that are not in a tagged version: https://github.com/qandidate-labs/qandidate-toggle-bundle/compare/1.1.2...master

**Comment by othillo** [comment]
Hey @eriwin , I tagged [1.2.0](https://github.com/qandidate-labs/qandidate-toggle-bundle/releases/tag/1.2.0).
