### ISSUE TITLE
Symfony 5 compatibility

### ISSUE THREAD

**Issue by bdsl** [qandidate-labs/qandidate-toggle-bundle#74]
Are there any plans to release a version of this that can be used with Symfony 5? The current version in master declares compatibility only with 2,3 and 4:

https://github.com/qandidate-labs/qandidate-toggle-bundle/blob/921806d5d270875e8dfc016e57cbd30e5361f7f1/composer.json#L27

**Comment by othillo** [comment]
Hi, @bdsl, the latest tag supports Symfony 5.

**Comment by bdsl** [comment]
Thanks @othillo.
