### ISSUE TITLE
Add support for Collections other then in_memory and redis 

### ISSUE THREAD

**Issue by ricbra** [qandidate-labs/qandidate-toggle-bundle#8]
Currently using the bundle with another storage then Redis is quite difficult. I tried the InMemoryCollection but basically its impossible to register toggles via the container configuration. While it's possible to add toggles via the <code>ToggleManager</code> as well as the <code>ToggleCollection</code> it's not supported to inject anything in there. 

A small summary of my journey so far:

My first attempt was to create a custom <code>ToggleCollection</code> and register it as <code>qandidate.toggle.collection.custom</code>. Then in config,yml I tried:

```yml
qandidate_toggle:
    persistence: custom
```

This would be registered in <code>QandidateToggleExtension</code> as:

```php
 $container->setAlias('qandidate.toggle.collection', 'qandidate.toggle.collection.' . $collection);
```
 But unfortunately the config prohibits anything else then <code>redis</code> and <code>in_memory</code>.

So what options are left? I could override <code>qandidate.toggle.collection.in_memory.class</code> parameter in my bundle.  Or override <code>qandidate.toggle.manager</code> service definition in my bundle. Both solutions are a bit hacky if you ask me.

So possible solutions I can think of:
- add a YmlCollection (or perhaps more generic FileCollection with support for xml, yml, php file etc.)
- add support for providing a custom collection factory (by service id) so users are completely free to build their toggle collection

Any thoughts on this? I'm glad to do some PR to fix this.

Also, the bundles documentation could use some love ;);

**Comment by ricbra** [comment]
ping @wjzijderveld

**Comment by wjzijderveld** [comment]
Hi @ricbra,

At this moment, those are the only 2 we have.
I agree there is quit some room for improvement there :-)

But I guess it wouldn't be that hard to write a wrapper for the InMemory collection that would fill it based on the contents of a file (like the YmlCollection you already mentioned).

The option to define your own collections would certainly be a possibility. Maybe by tagging them or something? 

I don't have time at the moment to think this through, so will be coming back to this :)

**Comment by ricbra** [comment]
I'll submit a PR with my idea about it, so you can shoot at it.

**Comment by asm89** [comment]
@ricbra 

> So possible solutions I can think of:
> - add a YmlCollection (or perhaps more generic FileCollection with support for xml, yml, php file etc.)

:+1: that would be a great addition to the bundle (maybe to the library as well?). Would you like to work on this?

> - add support for providing a custom collection factory (by service id) so users are completely free to build their toggle collection

:+1: for this too. We could make it possible to just set the service id you want to use.

**Comment by ricbra** [comment]
@asm89 No problem to work in this, I'll see what I can do this week.

**Comment by wjzijderveld** [comment]
Closing this now #9 has been merged.
